embeddedMySql: false

spring:
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://dev-platformdb.cnaaoeubjdx1.us-east-1.rds.amazonaws.com:3306/metric_service
    driverClassName: com.mysql.jdbc.Driver
    username: cygnusAdmin
    password: Neverquit#1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    ddl-auto: update